name: Python CI

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the environment

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python (specify version 3.9)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # You can change the version if needed (e.g., '3.8')

    # Step 3: Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib okx

    # Step 4: Run the Python script (replace trade.py with your actual script)
    - name: Run Python script
      run: |
        python trade.py  # Replace with the correct file name where your script resides
