name: Python CI

on:
  push:
    branches:
      - main  # Change to your target branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib TA-Lib okx

    - name: Run Python script
      run: |
        python trade.py  # Replace with the correct file name 
    
